version: "3"

services:
  my_service:
    build: .
    ports:
      - "${PORT}:${PORT}"
    environment:
      PORT: ${PORT}
    env_file:
      - .env
    depends_on:
      - db
      - redis

  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DBPASS}
      MYSQL_DATABASE: ${DBNAME}
      MYSQL_USER: ${DBUSER}
      MYSQL_PASSWORD: ${DBPASS}
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql

  redis:
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"

volumes:
  dbdata:
